# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Targettool < Formula
  desc "Simple tool for creating CSV target files"
  homepage "https://github.com/bxxf/target-gen"
  version "0.0.2"

  on_macos do
    url "https://github.com/bxxf/target-gen/releases/download/v0.0.2/target-gen_0.0.2_darwin_all.tar.gz"
    sha256 "ef7075a96388fda429caa9fca5b5aaf5ab76db6b691e82e9861b270d56078c54"

    def install
      bin.install "tgen"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bxxf/target-gen/releases/download/v0.0.2/target-gen_0.0.2_linux_arm64.tar.gz"
      sha256 "2b802ea3adabcd73641f8ea9618c7bdb1615c2cd84b92cccfd1a9205321b1022"

      def install
        bin.install "tgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bxxf/target-gen/releases/download/v0.0.2/target-gen_0.0.2_linux_amd64.tar.gz"
      sha256 "49584163be107abff93cd3e3c600a23041dafa43c8927a8f52b78940b2916eac"

      def install
        bin.install "tgen"
      end
    end
  end

  test do
    system "#{bin}/tgen"
  end
end
