# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tgen < Formula
  desc "Simple tool for creating CSV target files"
  homepage "https://github.com/bxxf/tgen"
  version "0.0.9"

  on_macos do
    url "https://github.com/bxxf/tgen/releases/download/v0.0.9/tgen_0.0.9_darwin_all.tar.gz"
    sha256 "34dd2dae45175f25daa346b6769a2d0133a7504e3f8ff9bf37b347182b5f9a98"

    def install
      bin.install "tgen"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bxxf/tgen/releases/download/v0.0.9/tgen_0.0.9_linux_arm64.tar.gz"
      sha256 "b714a0ab58fa7075eda6e9dea44bbf5a618313fa9ce3d393121d8fefb4624c73"

      def install
        bin.install "tgen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bxxf/tgen/releases/download/v0.0.9/tgen_0.0.9_linux_amd64.tar.gz"
      sha256 "0b34456261d9fbcccac2c3286586e54b4db4f343dffaa27661d190fb4de13bce"

      def install
        bin.install "tgen"
      end
    end
  end

  test do
    system "#{bin}/tgen"
  end
end
